POST http://localhost:3333/livros
Content-Type: application/json

{
    "titulo": "Livro 01",
    "autor": "Autor 01",
    "npaginas": 400
}

###

GET http://localhost:3333/livros

###

PUT http://localhost:3333/livros/02796176-c7b4-430b-942b-79f99f81e29d
Content-Type: application/json

{
    "titulo": "Livro 02",
    "autor": "Autor 02",
    "npaginas": 450
}


